---
- hosts: all
  become: yes
  tasks:
    - name: Full system upgrade
      become: yes
      apt:
        update_cache: yes
        upgrade: yes
    - name: Install CLI apps and libraries
      apt:
        name:
          - build-essential
          - software-properties-common
          - git
          - make
          - htop
          - iotop
          - rsync
        state: latest
    - name: Install Nginx
      apt:
        name:
          - nginx
        state: latest
    - name: Load Balancer configuration
      template:
        src: ./config-templates/default.j2
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: '0644'
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: reloaded
